server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/querydsl
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

